// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guamnmjwjhynqzwdfdjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1YW1ubWp3amh5bnF6d2RmZGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMDkwMzYsImV4cCI6MjA1Mjc4NTAzNn0.MycRMcg8NS8JqJQZGzW2PfGZsIClRTCOWc7XSzHW-KQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);